---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: 05vgoEEIooTRO60EQUuSb5V5ns63rJjhwQEx5sc1raERGd/Gvo3UGw==
---
kind: secret
name: docker_password
data: p1qO5lu8yGksl/igOB68waUXwiuMdybqSjKVvIEDAiTRqZQLyTiy3QhpgpDMIZDlCZ1T645kc1ZKe1RspaYS+w==
---
kind: secret
name: docker_username
data: YZ3vtZ9g2+q/QKbSEkJife89LnO6yLJRIRgbtXq7f0XSWxrYhxcCfg==
---
kind: secret
name: docker_password
data: c1dwAiYlczuU5GoxzBGI7shJPLxDY+nAgKEsnSLSGBAMZKPoMEzvP98Kf4GNUokFA5MDAktwU3cPciWYbQ4Aqw==
---
kind: signature
hmac: 59ede134cc7e6f98f888c855e09fd0cc189d3bdd28d45abd003f9ef7718f62f7

...
